feat: current

diff --git a/tama b/tama
--- a/tama
+++ b/tama
@@ -37,6 +37,7 @@ tama_usage() {
   printf "  %s   Trending anime\n" "trending "
   printf "  %s   Popular anime\n" "popular  "
   printf "  %s   Upcoming anime\n" "upcoming "
+  printf "  %s   Currently airing anime\n" "current  "
   printf "  %s   Search for a number of anime\n" "search   "
   printf "  %s   Watch an anime by episode\n" "watch    "
   printf "  %s   An anime's episodes\n" "episodes "
@@ -140,6 +141,38 @@ tama_upcoming_usage() {
   printf "%s\n" "Usage:"
   printf "  tama upcoming\n"
   printf "  tama upcoming --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+tama_current_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "tama current - Currently airing anime\n"
+    echo
+
+  else
+    printf "tama current - Currently airing anime\n"
+    echo
+
+  fi
+
+  printf "Alias: c\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  tama current\n"
+  printf "  tama current --help | -h\n"
   echo
 
   # :command.long_usage
@@ -431,6 +464,13 @@ tama_upcoming_command() {
 }
 
 # :command.function
+tama_current_command() {
+  # src/current_command.sh
+  print "/current"
+
+}
+
+# :command.function
 tama_search_command() {
   # src/search_command.sh
   print "/search/$(jq -rn --arg x "$(join "${args[query]}")" '$x | @uri')"
@@ -568,6 +608,13 @@ parse_requirements() {
       action="upcoming"
       shift
       tama_upcoming_parse_requirements "$@"
+      shift $#
+      ;;
+
+    current | c)
+      action="current"
+      shift
+      tama_current_parse_requirements "$@"
       shift $#
       ;;
 
@@ -743,6 +790,50 @@ tama_upcoming_parse_requirements() {
 
   # :command.command_filter
   action="upcoming"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+tama_current_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        tama_current_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="current"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -1068,6 +1159,7 @@ run() {
     "trending") tama_trending_command ;;
     "popular") tama_popular_command ;;
     "upcoming") tama_upcoming_command ;;
+    "current") tama_current_command ;;
     "search") tama_search_command ;;
     "watch") tama_watch_command ;;
     "episodes") tama_episodes_command ;;
